# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='friend',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='restaurant.Guest'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='restaurant.Guest'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='columns',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rows',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tables',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='column',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='row',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
